#pragma once
namespace ffmpegerr
{

	enum TFFMPEGErrorCodes
	{
		FFMPEG_CONVERTER_ERROR_SUCCESS = 0,
		FFMPEG_CONVERTER_ERROR_UNKNOWN = 1,
		FFMPEG_CONVERTER_ERROR_INTERNAL = 2,
		FFMPEG_CONVERTER_ERROR_INVALID_PRESET = 3,
		FFMPEG_CONVERTER_ERROR_INVALID_INPUT_FILE_NAME = 4,
		FFMPEG_CONVERTER_ERROR_INVALID_OUTPUT_FILE_NAME = 5,
		FFMPEG_CONVERTER_ERROR_UNDEFINED_INPUT_FILE = 6,
		FFMPEG_CONVERTER_ERROR_UNDEFINED_OUTPUT_FILE = 7,
		FFMPEG_CONVERTER_ERROR_OPEN_FAILED = 8,
		FFMPEG_CONVERTER_ERROR_DECODE_FAILED = 9,
		FFMPEG_CONVERTER_ERROR_UNSUPPORTED_CODEC = 10,
		FFMPEG_CONVERTER_ERROR_UNSUPPORTED_EXT_VIDEO_OPTIONS = 11,
		FFMPEG_CONVERTER_ERROR_UNSUPPORTED_EXT_AUDIO_OPTIONS = 12,
		FFMPEG_CONVERTER_ERROR_INVALID_EXT_VIDEO_OPTIONS = 13,
		FFMPEG_CONVERTER_ERROR_INVALID_EXT_AUDIO_OPTIONS = 14,
		FFMPEG_CONVERTER_ERROR_DAMAGED_INPUT_FILE = 15,
		FFMPEG_CONVERTER_ERROR_CODEC_MISSING = 16,
		FFMPEG_CONVERTER_ERROR_ENCODE_FAILED = 17,
		FFMPEG_CONVERTER_ERROR_LIBRARY_NOT_LOADED = 18,
		FFMPEG_CONVERTER_ERROR_INVALID_INPUT_ARGUMENT = 19,
		FFMPEG_CONVERTER_ERROR_NO_SPACE_ON_DEVICE = 20,

		FFMPEG_CONVERTER_ERROR_FFMPEG_OPEN_INPUT = 50,

		FFMPEG_CONVERTER_ERROR_FFMPEG_NOT_FOUND_EXE = 60,
		FFMPEG_CONVERTER_ERROR_UNKNOWN_AFTER_PROCESS_FINISHED = 70,

		FFMPEG_CONVERTER_ERROR_START                = 80,
        FFMPEG_CONVERTER_ERROR_DEDUCE_FORMAT = 81,


        FFMPEG_CONVERTER_ERROR_BEGIN_INPUT = 100,
        FFMPEG_CONVERTER_ERROR_DECODE_FRAME = 101,
        FFMPEG_CONVERTER_ERROR_END_INPUT = 102,

        FFMPEG_CONVERTER_ERROR_BEGIN_SINK = 103,
        FFMPEG_CONVERTER_ERROR_ENCODE_FRAME = 104,
        FFMPEG_CONVERTER_ERROR_END_SINK = 105,
	};

} //namespace ffmpegerr