#define CompanyName             "FlixGot"
#define CompanyDomain           "flixgot.com"
#define UpdatesURL              "https://" + CompanyDomain

#define version_url             "http://vending.freegrabapp.com/Administration/Products"


[Setup]

AppPublisher            = {#CompanyName} LLC
AppCopyright            = (C) 2021 - 2023 {#CompanyName} LLC
AppPublisherURL         = https://{#CompanyDomain}/bug-reporting/
AppSupportURL           = https://{#CompanyDomain}/bug-reporting/
