#define public CompanyName             "FreeGrabApp"
#define CompanyName             "FreeGrabApp"
#define public CompanyDomain           "freegrabapp.com"
#define public UpdatesURL              "https://download." + CompanyDomain

#define public version_url             "http://vending." + CompanyDomain + "/Administration/Products"

[Setup]

AppPublisher                    = {#CompanyName} LLC
AppCopyright                    = (C) 2013 - 2025 Technology LLC
AppPublisherURL                 = https://{#CompanyDomain}/bug-reporting/
AppSupportURL                   = https://{#CompanyDomain}/faq/
