#pragma once

namespace MMConv
{

enum EConvErrorCode
{
    CONV_ERROR_CODE_SUCCESS = 0,
    CONV_ERROR_CODE_UNKNOWN = 1,
    CONV_ERROR_CODE_INTERNAL = 2,
    CONV_ERROR_CODE_INVALID_PRESET = 3,
    CONV_ERROR_CODE_INVALID_INPUT_FILE_NAME = 4,
    CONV_ERROR_CODE_INVALID_OUTPUT_FILE_NAME = 5,
    CONV_ERROR_CODE_UNDEFINED_INPUT_FILE = 6,
    CONV_ERROR_CODE_UNDEFINED_OUTPUT_FILE = 7,
    CONV_ERROR_CODE_OPEN_FAILED = 8,
    CONV_ERROR_CODE_DECODE_FAILED = 9,
    CONV_ERROR_CODE_UNSUPPORTED_CODEC = 10,
    CONV_ERROR_CODE_UNSUPPORTED_EXT_VIDEO_OPTIONS = 11,
    CONV_ERROR_CODE_UNSUPPORTED_EXT_AUDIO_OPTIONS = 12,
    CONV_ERROR_CODE_INVALID_EXT_VIDEO_OPTIONS = 13,
    CONV_ERROR_CODE_INVALID_EXT_AUDIO_OPTIONS = 14,
    CONV_ERROR_CODE_DAMAGED_INPUT_FILE = 15,
    CONV_ERROR_CODE_CODEC_MISSING = 16,
    CONV_ERROR_CODE_ENCODE_FAILED = 17,
    CONV_ERROR_CODE_LIBRARY_NOT_LOADED = 18,
    CONV_ERROR_CODE_INVALID_INPUT_ARGUMENT = 19,
    CONV_ERROR_CODE_NO_SPACE_ON_DEVICE = 20,

    CONV_ERROR_CODE_FFMPEG_OPEN_INPUT = 50,

    CONV_ERROR_CODE_FFMPEG_NOT_FOUND_EXE = 60,
    CONV_ERROR_CODE_UNKNOWN_AFTER_PROCESS_FINISHED = 70,

    CONV_ERROR_CODE_START                = 80,
    CONV_ERROR_CODE_DEDUCE_FORMAT = 81,


    CONV_ERROR_CODE_BEGIN_INPUT = 100,
    CONV_ERROR_CODE_DECODE_FRAME = 101,
    CONV_ERROR_CODE_END_INPUT = 102,

    CONV_ERROR_CODE_BEGIN_SINK = 103,
    CONV_ERROR_CODE_ENCODE_FRAME = 104,
    CONV_ERROR_CODE_END_SINK = 105,
};

} //namespace MMConv
